name: Build & Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-dev:
    strategy:
      matrix:
        version: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Login on DockerHub registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker images
        run: docker build --build-arg PHP_VERSION=${{ matrix.version }} -t danybmx/php:${{ matrix.version }}-apache .
      - name: Push docker images
        run: docker push danybmx/php:${{ matrix.version }}-apache
  build-prod:
    strategy:
      matrix:
        version: ["7.4", "8.0", "8.1", "8.2"]
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Login on DockerHub registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker images
        run: docker build -f Dockerfile.prod --build-arg PHP_VERSION=${{ matrix.version }} -t danybmx/php:${{ matrix.version }}-prod-apache .
      - name: Push docker images
        run: docker push danybmx/php:${{ matrix.version }}-prod-apache
