name: Build & Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-dev:
    strategy:
      matrix:
        version: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: ${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login on DockerHub registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          build-args: |
            PHP_VERSION=${{ matrix.version }}
          tags: danybmx/php:${{ matrix.version }}-apache
  build-prod:
    strategy:
      matrix:
        version: ["7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: ${{ matrix.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login on DockerHub registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          file: Dockerfile.production
          build-args: |
            PHP_VERSION=${{ matrix.version }}
          tags: danybmx/php:${{ matrix.version }}-prod-apache
